import DashedBorder from "@/components/shared/dashed-border";
import { Description, H1, Title } from "@/components/ui/typography";

const privacySections = [
  {
    title: "1. Scope and purpose",
    content:
      "This Privacy Policy applies to personal data processed by Gamblio in the provision of the Gamblio Platform and Services, which include: Gamblio Analytics (BI and reporting); Gamblio Predict (player behavior modeling, segmentation, VIP, churn, bonus-hunter, responsible gaming signals); Gamblio uChoose (game recommendation engine); Gamblio Care (AI chat agent and Customer Care console); Integrations, widgets, SDKs, and managed streaming endpoints (Kafka / RabbitMQ); and Professional services (deployment, onboarding, custom integrations, support). It covers personal data provided directly by our Licensee (the gambling operator), data generated by end users interacting with Licensee platforms and Gamblio widgets, and certain information we collect when you interact with Gamblio's own websites, support channels or marketing materials. Our handling of personal data is guided by strict management and security standards, including ISO 9001:2015 for quality management, ISO/IEC 27001:2022 for information security, and ISO/IEC 42001:2023 for responsible AI management, ensuring processes are robust, controlled, and continually improved.",
  },
  {
    title: "2. Key principles",
    content:
      "We commit to: Processing personal data only for specified, explicit, and legitimate purposes; Minimizing the amount of personal data collected and processed; Implementing reasonable technical and organizational measures to protect personal data, in line with our ISO 9001, ISO 27001, and ISO 42001 certified management systems; Assisting customers (Licensees) in meeting their legal obligations (e.g. responding to data subject rights requests, recordkeeping); and Not using personal data for secondary purposes incompatible with the original purpose without appropriate legal basis or consent.",
  },
  {
    title: "3. What personal data we collect",
    content:
      "Data types processed depend on the service and the integration model used by the Licensee. Data may be provided directly by the Licensee via streaming (Kafka/RabbitMQ), API, or widgets, or derived from those inputs. Player / End-user data includes: Identifiers (player ID, First name, Last name, username, email address, phone number, external identifiers); Authentication & access data; Contact & account info; Personal attributes; Financial & transactional data; Gaming & behavioral data; Bonus & promotions data; Support & communication data; Risk & compliance signals; and Derived data / models (churn scores, VIP scores, prediction outputs, segment labels, propensity scores, and other profiling outputs generated by Gamblio models).",
  },
  {
    title: "4. GDPR Compliance",
    content:
      "Gamblio is committed to complying with the European Union General Data Protection Regulation (GDPR) (Regulation (EU) 2016/679) in all processing of personal data originating from the EU/EEA. As part of this commitment: All personal data is processed lawfully, fairly, and transparently, with clear legal bases such as performance of contract, consent, legitimate interests, or legal obligations. Individuals have the right to access, rectify, erase, restrict, or object to processing of their personal data, as well as the right to data portability and to lodge complaints with supervisory authorities. Gamblio cooperates with Licensees to facilitate these rights. Only data necessary for the defined services and purposes is collected and processed, in line with GDPR principles. Technical and organizational measures follow ISO/IEC 27001:2022, ISO 9001:2015, and ISO/IEC 42001:2023 standards to ensure confidentiality, integrity, and availability of personal data.",
  },
  {
    title: "5. Sources of data",
    content:
      "We obtain personal data from: Licensees / Operators — primary source: via streaming (Kafka/RabbitMQ), REST APIs, direct database import (historical data import only, optional), or widget SDKs/snippets embedded in the operator's platform; End users — when interacting with operator platforms that use Gamblio widgets (e.g., chat widget or recommendation widget) or when providing data to the operator; Third parties — payment processors, identity verification vendors, fraud and AML providers, public sources or partners, as authorized by our Licensee; and Gamblio systems — automatically generated logs and model outputs.",
  },
  {
    title: "6. Purposes of processing",
    content:
      "We process personal data to provide and improve our Services, including but not limited to: Service delivery & platform operation; Analytics & BI; Predictions & segmentation; Recommendations; Customer support; Fraud, risk & compliance; Security & reliability; Billing, invoicing & contract management; Legal & regulatory obligations; Product improvement & research; and Marketing & communications.",
  },
  {
    title: "7. Legal bases for processing",
    content:
      "Where applicable (e.g., under EU/EEA data protection laws), Gamblio relies on the following legal bases: Performance of contract: processing necessary to perform the Agreement with the Licensee; Legitimate interests: for operations, security, fraud detection, and system improvement; Consent: where required for optional marketing or certain tracking cookies on Gamblio websites; Legal obligation: to comply with legal or regulatory requirements; and Legal necessity for compliance or defense: where needed to respond to legal claims or investigations.",
  },
  {
    title: "8. Recipients & subprocessors",
    content:
      "To deliver the Services, Gamblio may share personal data with: Our subprocessors / service providers, including but not limited to: cloud hosting providers, managed Kafka/RabbitMQ services, CDN and SDK providers, payment and identity service integrators (as instructed by Licensee), analytics and monitoring services, and outsourced support providers; Licensee-authorized third parties (e.g., affiliates, consultants) with prior authorization; Law enforcement, regulators or courts when legally required; and Prospective buyers, advisors in the event of M&A (with contractual safeguards).",
  },
  {
    title: "9. International transfers",
    content:
      "Gamblio operates globally. Personal data may be transferred or accessed outside the Licensee's jurisdiction, including to countries that may not provide the same level of data protection as the country of origin. Where transfers occur, we implement appropriate safeguards such as: Standard Contractual Clauses (SCCs) or other approved transfer mechanisms; Adequate technical and organizational safeguards (encryption, access controls); Hosting in customer-specific, isolated environments when requested and agreed; and Where required by local law, additional contractual assurances.",
  },
  {
    title: "10. Data retention and deletion",
    content:
      "We retain personal data only as long as necessary to fulfill the purposes described in this Policy, or as required by contract or law. Retention specifics: Operational / transactional data: retained for the period required by the Licensee and for billing, auditing, and dispute resolution (default: 5 years, but dependable on terms signed in SLA). Model training data & derived models: retained in pseudonymized or aggregated form as needed to improve services. Support & chat transcripts: retained for a configurable period to meet operational and compliance needs. Marketing & website cookies: retention depends on cookie type; consented cookies are retained per user selection.",
  },
  {
    title: "11. Security measures",
    content:
      "We maintain industry-standard technical and organizational measures to protect personal data, including: ISO 27001 certified information security management; Network and application firewalls, intrusion detection and prevention; Encryption of data in transit (TLS) and at rest (AES-256 or equivalent); Role-based and least privilege access controls (RBAC); Strong authentication mechanisms for administrative access (2FA); Regular security testing, vulnerability scanning, and patch management; Logging, monitoring, and incident response processes; and Data minimization and pseudonymization where possible.",
  },
  {
    title: "12. Automated decision-making and profiling",
    content:
      "Gamblio uses automated processing and profiling (machine learning models) to score and segment players (e.g., churn prediction, VIP scoring, bonus-hunter classification, RG risk). These outputs are used to inform operator actions (e.g., targeted offers, agent interventions). Human oversight & transparency: Gamblio surfaces model explanations, confidence levels, and the features that contributed to a prediction to help Licensees understand model outputs. Operator control & overrides: Licensees retain the ability to review, adjust, or override automated decisions.",
  },
  {
    title: "13. Data subject rights",
    content:
      "Depending on applicable law, data subjects (players / end users) may have rights including, but not limited to: Right to access their personal data; Right to rectification; Right to erasure ('right to be forgotten'); Right to restriction of processing; Right to data portability; Right to object to processing (including profiling) based on legitimate interests; Right to withdraw consent where consent is the legal basis; and Right to lodge a complaint with a supervisory authority. In most cases, players should contact the gambling operator (the data controller) to exercise their rights.",
  },
  {
    title: "14. Cookies, tracking & web analytics",
    content:
      "Gamblio's website and widgets may use cookies and similar technologies for: Essential functionality (session cookies); Performance and analytics (e.g., platform usage metrics that help us improve services); and Marketing and personalization (only with consent where required). Our widgets can be configured by Licensees to pass identifiers or session tokens so Gamblio can provide personalized recommendations or chat history.",
  },
  {
    title: "15. Children",
    content:
      "The Services are intended for use by adults in regulated gambling environments. We do not knowingly collect personal data of children under the legal gambling age applicable in the player's jurisdiction. If we become aware that we have collected personal data of a person under the applicable legal gambling age, we will take steps to delete that data and notify the Licensee.",
  },
  {
    title: "20. Data protection officer & contact",
    content:
      "If you have questions about this Privacy Policy, to request records, or to exercise data subject rights, contact: Data Protection Officer (DPO) Email: privacy@gamblio.ai (or DPO contact specified in contract) Postal: GAMBLIO LLC, Miloja Pavlovića Street No. 110, Podgorica, Montenegro. For operational or technical enquiries (Licensees / integrators), please use your assigned Customer Success contact or support@gamblio.ai. If you are an end user (player), please contact the operator (the platform where you play) in the first instance to exercise rights; Gamblio will cooperate with the operator to fulfill lawful requests.",
  },
];

export default function PrivacyPolicyPage() {
  return (
    <div className="w-full my-24 border-b-0">
      <DashedBorder
        sides="all"
        className="flex flex-col items-center gap-4 py-12"
      >
        <H1 className="font-medium text-center md:text-3xl lg:text-4xl">
          Gamblio Privacy Policy
        </H1>
        <Description className="text-base text-center text-muted-foreground md:w-1/2">
          Effective date: 30.12.2025 | Last updated: 30.12.2025
        </Description>
        <Description className="text-sm text-center text-muted-foreground md:w-2/3 mt-4">
          Controller / Data Processor: "GAMBLIO" LLC PODGORICA (hereinafter
          "Gamblio", "we", "us", or "our") | Registered office: Miloja Pavlovića
          Street No. 110, Podgorica, Montenegro | TIN: 03683923
        </Description>
        <Description className="text-sm text-center text-muted-foreground md:w-2/3 mt-2">
          If you are a customer or user of a gambling operator that uses
          Gamblio, your relationship regarding personal data will typically
          involve three parties: (1) the player / end user; (2) the gambling
          operator (our direct customer, often the data controller); and (3)
          Gamblio (the data processor or, depending on the service, a joint
          controller). This Privacy Policy explains how Gamblio collects, uses,
          stores, shares, and protects personal data in connection with the
          Gamblio Platform and Services.
        </Description>
      </DashedBorder>
      <DashedBorder sides="all">
        <div className="w-full  space-y-6">
          {privacySections.map((section, index) => (
            <DashedBorder
              key={index}
              sides="all"
              className="flex flex-col items-start gap-4 p-6"
            >
              <Title className="text-xl text-left font-semibold">
                {section.title}
              </Title>
              <Description className="text-left text-muted-foreground text-balance">
                {section.content}
              </Description>
            </DashedBorder>
          ))}
        </div>
      </DashedBorder>
    </div>
  );
}
