import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navigation/navbar";
import { Footer } from "@/components/navigation/footer";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets:['latin']
});

export const metadata: Metadata = {
  title: "Gamblio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} dark grid items-center justify-center   antialiased`}
      >
        <NavBar />
        <div className="container overflow-hidden divide-y divide-dashed max-w-7xl border-x border-dashed relative">
          {children}

          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
