import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/navigation/footer";
import NavBar from "@/components/navigation/navbar";
import DashedBorder from "@/components/shared/dashed-border";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gamblio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} dark antialiased w-full overflow-x-hidden`}
      >
        <NavBar />
        <DashedBorder
          sides="x"
          className="w-full pt-0 divide-y divide-dashed md:mx-0"
        >
          {children}
          <Footer />
        </DashedBorder>
        <Toaster />
      </body>
    </html>
  );
}
