import type { Metadata } from "next";
import DashedBorder from "@/components/shared/dashed-border";
import { Description, H1, Title } from "@/components/ui/typography";
import { createMetadata } from "@/lib/metadata";

export const metadata: Metadata = createMetadata({
  title: "Terms of Service - Gamblio Platform Terms and Conditions",
  description:
    "Gamblio Terms of Service govern the use of our AI-powered platform for gambling operators. Learn about licensing, data processing, security, intellectual property, and service agreements.",
  path: "/terms-of-service",
  keywords: [
    "Gamblio terms of service",
    "gambling platform terms",
    "casino software license",
    "service agreement gambling",
    "platform terms and conditions",
  ],
  noIndex: false,
});

const termsSections = [
  {
    title: "1. Definitions",
    content:
      "Agreement – These Terms, together with any Order Form, License Agreement (LA), Service License Agreement (SLA), or any other written contract between the Parties. Services – The Gamblio Platform and all related modules, including Analytics, Predict, uChoose, Care, integrations, SDKs, widgets, hosting, support, and professional services. Licensee / Operator – The legal entity contracting with Gamblio and responsible for player data and local regulatory compliance. Player Data – Personal data collected by the Operator and shared with Gamblio via APIs, SDKs, streaming, or database import. Models / ML Outputs – Predictive scoring, segmentation, personalized recommendations, or automated insights generated by Gamblio.",
  },
  {
    title: "2. Scope of Services",
    content:
      "Gamblio provides operators with: Analytics and business intelligence dashboards; Predictive modeling and automated segmentation; Personalized recommendation services; AI-powered customer support and chat tools; Integrations, ingestion APIs, SDKs, widgets, and event streams; and Professional and onboarding services. Gamblio may update, improve, or modify Services from time to time, provided such changes do not materially degrade core functionalities available at the time of contracting. All Services are delivered under ISO 9001:2015 quality management, ISO/IEC 27001:2022 information security, and ISO/IEC 42001:2023 responsible AI management standards.",
  },
  {
    title: "3. License Grant",
    content:
      "Subject to these Terms and timely payment of applicable fees, Gamblio grants the Licensee a non-exclusive, non-transferable, non-sublicensable, limited right to access and use the Services solely for internal business operations of the Licensee and solely in connection with the Licensee's regulated gambling platform(s). No rights are granted to access Gamblio's source code, algorithms, or proprietary technologies.",
  },
  {
    title: "4. Customer Responsibilities",
    content:
      "The Licensee agrees to: Provide accurate data - Ensure all data sent to Gamblio (Player Data, transactional data, events, metadata) is accurate, lawful, and in accordance with regulatory obligations. Maintain regulatory compliance - The Licensee is solely responsible for gambling licensing requirements, responsible gaming obligations, AML and fraud compliance, jurisdictional data processing laws, and player rights and disclosures. Manage user access - The Licensee must ensure that only authorized employees access the Gamblio system and that credentials are kept confidential. Use Services lawfully - The Licensee must not use the Services to violate gambling or data protection laws, exploit system vulnerabilities, build competing services, infringe third-party rights, or interfere with platform operation.",
  },
  {
    title: "5. Machine Learning Outputs & Automated Decisions",
    content:
      "Gamblio may produce automated insights such as: Churn risk, VIP scoring, Bonus-hunter classifications, Player segmentation, Recommendation rankings, and Responsible gambling or risk alerts. These outputs are informational and do not constitute instructions or orders. The Licensee retains full control over all decisions relating to Players, must apply human judgment where legally required, and is responsible for compliance with laws around automated processing. Gamblio is not liable for business decisions made by the Licensee based on ML outputs. All AI models and automated decision-making processes are developed, maintained, and operated in accordance with ISO/IEC 42001:2023.",
  },
  {
    title: "6. Data Processing & Security",
    content:
      "Processing of personal data is governed by the Service License Agreement. Key points include: Gamblio acts as a processor for Player Data; Licensee remains controller and responsible for legal basis, notices, and consents; Gamblio uses industry-standard security measures (ISO 27001); Subprocessors may be engaged as specified in the Subprocessor List; and Data is retained only as long as necessary per the Agreement. If there is a conflict between these Terms and the SLA, the SLA prevails for all data protection matters.",
  },
  {
    title: "7. Integrations & Third-Party Dependencies",
    content:
      "The Licensee acknowledges that: The Services require stable data ingestion from Licensee systems; Any failure of the Licensee's systems, feeds, APIs, or streaming layers may degrade Gamblio's output quality or availability; and Gamblio is not liable for failures caused by Licensee systems, network issues, or third-party providers.",
  },
  {
    title: "8. Fees, Billing & Payment",
    content:
      "Licensee agrees to pay all fees specified in the Order Form, which may include: Subscription fees, Usage-based fees, Per-module fees, Setup, onboarding, or integration fees, Overages beyond agreed usage limits, and Optional customization fees. Unless specified otherwise: Invoices are payable within 30 days, Late payments may incur interest, and Unpaid accounts may be suspended. All fees are non-refundable, except where required by law or explicitly stated otherwise.",
  },
  {
    title: "9. Intellectual Property",
    content:
      "Gamblio retains all ownership rights in: The platform and its components; Software, code, algorithms, models, and ML pipelines; Documentation, UI, dashboards, and designs; and Aggregated statistics and anonymized analytics. Licensee retains ownership of its: Player Data; Business insights derived from using the Services; and Data delivered to Gamblio. No IP rights are transferred to the Licensee.",
  },
  {
    title: "10. Confidentiality",
    content:
      "Each Party agrees to: Protect confidential information using reasonable safeguards; Use such information only for fulfilling the Agreement; and Not disclose confidential information to third parties, except subprocessors or authorized personnel under confidentiality obligations. Confidentiality obligations survive termination.",
  },
  {
    title: "11. Service Availability & SLA",
    content:
      "Gamblio strives to maintain high availability. Where applicable, uptime commitments, response times, and support processes are defined in the SLA. Gamblio is not responsible for downtime caused by: The Licensee's infrastructure; Internet failures; Misuse or incorrect configuration; Force majeure events; or Third-party services outside Gamblio's control. All operational procedures are maintained under ISO 9001:2015 quality standards.",
  },
  {
    title: "12. Warranties & Disclaimers",
    content:
      "Gamblio provides the Services 'as is' and 'as available.' We do not warrant that: The Services will be error-free or uninterrupted; Predictions or insights will always be accurate; Integration will produce specific commercial results; or ML models will fit the Licensee's risk or business strategy. To the maximum extent permitted by law, all implied warranties are excluded.",
  },
  {
    title: "13. Limitation of Liability",
    content:
      "To the fullest extent permitted by law: Gamblio is not liable for: Loss of profits, revenue, or business; Errors in the Licensee's systems or data; Regulatory penalties caused by Licensee actions; Decisions made by Licensee based on ML outputs; or Indirect, special, incidental, or consequential damages. Gamblio's total liability is limited to the amount paid by the Licensee to Gamblio in the 12 months preceding the claim.",
  },
  {
    title: "14. Suspension of Services",
    content:
      "Gamblio may suspend access if: The Licensee violates laws or these Terms; The Licensee materially misuses the platform; Payment is overdue; or Continued use poses security or operational risks. Gamblio will notify the Licensee where reasonable.",
  },
  {
    title: "15. Term & Termination",
    content:
      "The Agreement begins when the Licensee first accesses the Services and continues until terminated as described here or per the Order Form. Either party may terminate for: Material breach not cured within 30 days; or Insolvency or cessation of business. Upon termination: Access to the Services is discontinued; Licensee must cease all use of the platform; Gamblio will delete or return Player Data as agreed in the SLA; and All outstanding payments become immediately due.",
  },
  {
    title: "16. Publicity",
    content:
      "Gamblio may reference the Licensee's company name and logo in marketing materials, unless the Licensee opts out in writing. Operators may publicly reference Gamblio as a technology provider.",
  },
  {
    title: "17. Governing Law & Jurisdiction",
    content:
      "These Terms are governed by the laws of Montenegro, without regard to conflict of laws principles. Any disputes arising under these Terms shall be resolved exclusively in the competent courts of Podgorica, Montenegro.",
  },
  {
    title: "18. Changes to Terms",
    content:
      "Gamblio may update these Terms periodically. Material changes will be communicated to Licensees. Continued use of the Services after changes take effect constitutes acceptance of the updated Terms.",
  },
  {
    title: "19. Entire Agreement",
    content:
      "These Terms, together with the Order Form, LA, and SLA, constitute the entire agreement between the Parties and supersede all prior agreements or communications.",
  },
  {
    title: "20. Contact",
    content:
      "For questions about these Terms, please contact: GAMBLIO LLC, Miloja Pavlovića Street No. 110, 81000, Podgorica, Montenegro. Email: support@gamblio.ai",
  },
];

export default function TermsOfServicePage() {
  return (
    <div className="w-full my-24 border-b-0">
      <DashedBorder
        sides="all"
        className="flex flex-col items-center gap-4 py-12"
      >
        <H1 className="font-medium text-center md:text-3xl lg:text-4xl">
          GAMBLIO – TERMS OF SERVICE (TOS)
        </H1>
        <Description className="text-base text-center text-muted-foreground md:w-1/2">
          Effective Date: 30.12.2025 | Last Updated: 30.12.2025
        </Description>
        <Description className="text-sm text-center text-muted-foreground md:w-2/3 mt-4">
          These Terms of Service ("Terms") govern the use of the Gamblio
          platform, products, and services ("Services") provided by GAMBLIO LLC
          PODGORICA ("Gamblio," "we," "us," or "our"). By accessing or using our
          Services, the Customer ("Licensee," "Operator," "Client," or "you")
          agrees to these Terms. If you do not agree to these Terms, you must
          not use the Services.
        </Description>
      </DashedBorder>
      <DashedBorder sides="all">
        <div className="w-full  space-y-6">
          {termsSections.map((section) => (
            <DashedBorder
              key={section.title}
              sides="all"
              className="flex flex-col items-start gap-4 p-6"
            >
              <Title className="text-xl text-left  font-semibold">
                {section.title}
              </Title>
              <Description className="text-left text-muted-foreground text-balance">
                {section.content}
              </Description>
            </DashedBorder>
          ))}
        </div>
      </DashedBorder>
    </div>
  );
}
